"""Remove development residue from the data directory.

Everything this deletes is either a temporary corpus generated by the check scripts
or a log written by them. It deliberately refuses to touch anything that is not on an
explicit allowlist, so it cannot remove a real workspace.

    python scripts/clean_workspace.py --dry-run
    python scripts/clean_workspace.py
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

# Explicit allowlist. A glob would be one typo away from deleting real data.
TEMP_DIRECTORIES = [
    "_debug",
    "_e2e",
    "_http_corpus",
    "_probe_corpus",
    "_probe_ws",
]
TEMP_FILES = [
    "e2e-server.log",
    "probe-upload.log",
]

# Never removed: the live database, the workspaces themselves, backups, the vector
# index, and the running services' logs.
PROTECTED = {"app.db", "app.db-shm", "app.db-wal", "workspaces", "backups", "qdrant"}


def resolve_target(name: str) -> Path:
    target = (DATA / name).resolve()
    if target.parent != DATA.resolve():
        raise ValueError(f"refusing to act outside the data directory: {target}")
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="list without deleting")
    args = parser.parse_args()

    if not DATA.exists():
        print(f"no data directory at {DATA}")
        return 0

    removed_dirs = 0
    removed_files = 0

    for name in TEMP_DIRECTORIES:
        if name in PROTECTED:
            print(f"skip protected entry: {name}")
            continue
        target = resolve_target(name)
        if not target.exists():
            continue
        if args.dry_run:
            print(f"would remove directory: {target.relative_to(ROOT)}")
        else:
            shutil.rmtree(target, ignore_errors=True)
            print(f"removed directory: {target.relative_to(ROOT)}")
            removed_dirs += 1

    for name in TEMP_FILES:
        target = resolve_target(name)
        if not target.exists():
            continue
        if args.dry_run:
            print(f"would remove file: {target.relative_to(ROOT)}")
        else:
            target.unlink(missing_ok=True)
            print(f"removed file: {target.relative_to(ROOT)}")
            removed_files += 1

    if args.dry_run:
        print("\n(dry run: nothing was deleted)")
    else:
        print(f"\nremoved {removed_dirs} director(ies) and {removed_files} file(s)")
        print("kept: app.db, workspaces/, backups/, qdrant/, backend*.log, frontend*.log")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
